### ISSUE TITLE
What is the proper way of installing this script to an existing Foxx app?

### ISSUE THREAD

**Issue by ilearnio** [arangodb/foxx-oauth2#1]
I tried:

```
$ npm install --save arangodb-foxx/util-oauth2
npm ERR! No name provided in package.json
```

Should I just download it into some `vendor/util-oauth2` folder or maybe there is some more correct way to do that? Thanks!

**Comment by ilearnio** [comment]
Oh... I should have read the readme carefully first. It's all there. Sorry for disturbing

**Comment by pluma** [comment]
No problem. If you are using ArangoDB 3.0 the OAuth2 functionality is actually built into Foxx now. The API is currently undocumented but should be fully functional.

Just `require('@arangodb/foxx/oauth2')`, which returns a function that takes an object with the same attributes as the configuration of this service. The function returns an object providing the same API as this service does for the given configuration.

**Comment by ilearnio** [comment]
That's great! I will try to upgrade to 3.0. Thank you!
